# Generated by Django 4.2.7 on 2025-11-15 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import documents.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=documents.models.document_upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.IntegerField(help_text='Taille du fichier en octets')),
                ('predicted_class', models.CharField(blank=True, choices=[('factures', 'Factures'), ('contrats', 'Contrats'), ('cartes_identite', "Cartes d'identité")], max_length=50, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('probability_factures', models.FloatField(blank=True, null=True)),
                ('probability_contrats', models.FloatField(blank=True, null=True)),
                ('probability_cartes_identite', models.FloatField(blank=True, null=True)),
                ('extracted_text', models.TextField(blank=True, help_text='Texte avec formatage (retours à la ligne)', null=True)),
                ('extracted_text_raw', models.TextField(blank=True, help_text='Texte brut pour BERT', null=True)),
                ('text_length', models.IntegerField(blank=True, null=True)),
                ('structured_data', models.JSONField(blank=True, help_text='Données structurées extraites', null=True)),
                ('processed', models.BooleanField(default=False)),
                ('processing_time', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=100)),
                ('details', models.JSONField(blank=True, null=True)),
                ('success', models.BooleanField(default=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='documents.document')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classification_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['owner', '-uploaded_at'], name='documents_d_owner_i_8b696e_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['predicted_class'], name='documents_d_predict_a28c30_idx'),
        ),
    ]
